version: "3.8"

services:
  easy-circulars-retriever:
    image: easy-circulars/retriever:latest
    container_name: easy-circulars-retriever
    ports:
      - "5011:7000"
    ipc: host
    depends_on:
      - easy-circulars-redis
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      REDIS_URL: ${REDIS_URL}
      INDEX_NAME: ${INDEX_NAME}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      TEI_EMBEDDING_ENDPOINT: http://easy-circulars-embedding-service:80
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
    restart: unless-stopped

  easy-circulars-redis:
    image: redis/redis-stack:7.2.0-v9
    container_name: easy-circulars-redis
    ports:
      - "6381:6379"
      - "8002:8001"

  easy-circulars-dataprep:
    image: easy-circulars/dataprep:latest
    container_name: easy-circulars-dataprep
    depends_on:
      - easy-circulars-redis
      - easy-circulars-embedding-service
    volumes:
      - "./cache:/.cache"
      - ${DATAPREP_OUT_DIR}:/home/user/comps/dataprep/out
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      REDIS_URL: ${REDIS_URL}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      LOGFLAG: ${LOGFLAG}
      TEI_EMBEDDING_ENDPOINT: http://easy-circulars-embedding-service:80
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      LLM_SERVER_HOST_IP: ${LLM_SERVER_HOST_IP}
      LLM_SERVER_PORT: ${LLM_SERVER_PORT:-80}
    ports:
      - "5012:6007"
    ipc: host
    restart: unless-stopped

  easy-circulars-groq:
    image: easy-circulars/groq:latest
    container_name: easy-circulars-groq
    ports:
      - "5101:8000"
    volumes:
      - "./cache:/root/.cache"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      GROQ_API_KEY: ${GROQ_API_KEY}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}

  easy-circulars-tei-reranking:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
    container_name: easy-circulars-tei-reranking
    ports:
      - "8810:80"
    volumes:
      - "./data:/data"
    shm_size: 1g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      HF_HUB_DISABLE_PROGRESS_BARS: 1
      HF_HUB_ENABLE_HF_TRANSFER: 0
    command: --model-id ${RERANK_MODEL_ID} --auto-truncate

  easy-circulars-embedding-service:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
    container_name: easy-circulars-embedding-service
    ports:
      - "6010:80"
    volumes:
      - "./data:/data"
    shm_size: 1g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HTTP_PROXY: ${HTTP_PROXY}
      HTTPS_PROXY: ${HTTPS_PROXY}
    command: --model-id ${EMBEDDING_MODEL_ID} --auto-truncate

  easy-circulars-mongodb:
    image: mongo
    container_name: easy-circulars-mongodb
    restart: always
    ports:
      - "27018:27017"

  easy-circulars-backend:
    image: easy-circulars/backend:latest
    depends_on:
      - easy-circulars-redis
      - easy-circulars-embedding-service
      - easy-circulars-retriever
      - easy-circulars-tei-reranking
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - MEGA_SERVICE_HOST_IP=127.0.0.1
      - MEGA_SERVICE_PORT=${MEGA_SERVICE_PORT}
      - EMBEDDING_SERVER_HOST_IP=${EMBEDDING_SERVER_HOST_IP}
      - EMBEDDING_SERVER_PORT=${EMBEDDING_SERVER_PORT:-80}
      - RETRIEVER_SERVICE_HOST_IP=${RETRIEVER_SERVICE_HOST_IP}
      - RETRIEVER_SERVICE_PORT=${RETRIEVER_SERVICE_PORT}
      - RERANK_SERVER_HOST_IP=${RERANK_SERVER_HOST_IP}
      - RERANK_SERVER_PORT=${RERANK_SERVER_PORT:-80}
      - LLM_SERVER_HOST_IP=${LLM_SERVER_HOST_IP}
      - LLM_SERVER_PORT=${LLM_SERVER_PORT:-80}
      - LLM_MODEL=${LLM_MODEL_ID}
      - LOGFLAG=${LOGFLAG}
      - MONGO_HOST=${MONGO_HOST}
    ipc: host
    ports:
      - "5013:5008"
    restart: always

  easy-circulars-ui:
    image: easy-circulars/ui:latest
    depends_on:
      - easy-circulars-backend
    ports:
      - "5014:3000"
    restart: always

networks:
  default:
    driver: bridge
